### ISSUE TITLE
Database restore failed with error.

### ISSUE THREAD

**Issue by nj3110** [pgbackrest/pgbackrest#543]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.02

2. PostgreSQL version: 9.6.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.4.1708 (Core)

4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Getting below mentioned error while trying to restore a database from backup.
----------------------------
[fsepuser@c7m1 inst2]$ pgbackrest --stanza=PD2 --delta --db-include=test restore
ERROR: [124]: process terminated due to an unhandled exception:
Use of uninitialized value $strDbFilter in concatenation (.) or string at /usr/share/perl5/pgBackRest/Restore.pm line 1224.
 at /usr/share/perl5/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('Use of uninitialized value $strDbFilter in concatenation (.) ...') called at /usr/share/perl5/pgBackRest/Restore.pm line 1224
        pgBackRest::Restore::process('pgBackRest::Restore=HASH(0x2941a28)') called at /usr/share/perl5/pgBackRest/Main.pm line 220
        eval {...} called at /usr/share/perl5/pgBackRest/Main.pm line 276
        pgBackRest::Main::main('restore') called at (eval 77) line 1
        eval '($result, $message) = pgBackRest::Main::main(\'restore\')
;' called at (eval 77) line 0

[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/2096699/pgbackrest.conf.txt)
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/2096700/postgresql.conf.txt)

**Comment by dwsteele** [comment]
Does your cluster only have one user database (excluding template* and postgres)? 
```
select datname, oid from pg_database;
```
If so, there's much much need to do a `--db-include`.  We'll fix the bug, of course, but if you add another database it should work.

**Comment by cmwshang** [comment]
@nj3110 The email from David's comment had a typo (I see he's fixed the comment in the GitHub thread) but I didn't see an email with the correction, so please check GitHub.

**Comment by cmwshang** [comment]
You took a backup AFTER you dropped the database, so that backup will contain your drop statement.  In your scenario you would do PITR restore to the time BEFORE the drop statement. See https://pgbackrest.org/user-guide.html#pitr for more information.

**Comment by cmwshang** [comment]
Edited my previous comment as I had a typo.

**Comment by dwsteele** [comment]
Fix committed at 4e7692b74d229538f.

**Comment by nj3110** [comment]
Hello 
Many thanks for your help. 
I tried to restore database with Point in time recovery as mentioned below. But still getting error [FATAL:  database "test" does not exist (10571)] when connecting to database.

------------------------------------------------------------------
STEP 1-
------
db created and test record inserted : Fri Jun 15 11:38:43 AEST 2018

postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/fsepuser          +
           |          |          |             |             | fsepuser=CTc/fsepuser
 template1 | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/fsepuser          +
           |          |          |             |             | fsepuser=CTc/fsepuser
 test      | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 test1     | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
(5 rows)


STEP 2-
------
Full Backup started : Fri Jun 15 11:45:00 AEST 2018
Full Backup Completed : Fri Jun 15 11:45:25 AEST 2018

 pgbackrest --stanza=PD2 --log-level-console=detail --db-port=5102 --type=full backup

 
STEP 3-
------
Drop Database - test :  Fri Jun 15 11:49:25 AEST 2018

STEP 4-
------
stop pg cluster 
Restored database with below mentioned command 
 pgbackrest --stanza=PD2 --delta --type=time "--target=2018-06-15 11:45:10" restore

STEP 5-
------
Start pg cluster and check if database is restored.

=> I could find database in database list
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/fsepuser          +
           |          |          |             |             | fsepuser=CTc/fsepuser
 template1 | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/fsepuser          +
           |          |          |             |             | fsepuser=CTc/fsepuser
 test      | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 test1     | fsepuser | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
(5 rows)


=> I faced below mentioned error while connecting to database.

postgres=# \c test
FATAL:  database "test" does not exist (10571)
DETAIL:  The database subdirectory "base/24583" is missing. (14619)
Previous connection kept

**Comment by dwsteele** [comment]
This doesn't look like a valid PITR time to me.  The time must be *after* backup end -- it's not possible to play to the middle of a backup.  You can check the postgres logs (described here: https://pgbackrest.org/user-guide.html#pitr) to see if PITR succeeded.

Did you create the cluster and databases fresh or were you working from a previous attempt?  I'm not sure why you are getting the error, whether PITR succeeded or not.  It's like the `drop database` was only partially replayed.

**Comment by dwsteele** [comment]
Glad you got it working!  We'll get the fix into the next release but we won't rush it since it's not critical.
